### ISSUE TITLE
Workshop FOSS4G-EU 2017 file/flows to use

### ISSUE THREAD

**Issue by sgrellet** [BRGM/gml_application_schema_toolbox#12]
An issue to where to add material for the workshop.
# BRGM 
(at least)
- content from our Groundwater Information Network (GIN): piezometers (INSPIRE EF) and associated WaterML2 TimeSeries
ex URI : http://ressource.brgm-rec.fr/data/Piezometre/06512X0037/STREMY.2
ex WFS : https://wfspoc.brgm-rec.fr/geoserver/ows?service=wfs&version=2.0.0&request=GetFeature&typenames=ef:EnvironmentalMonitoringFacility&count=10

- content from EU H2020 EPOS Research Infrastructure : EU BoreholeIndex. 
ad-hoc OGC SimpleFeature model linking to GIN above and also boreholeLogs (OGC:GroundWaterML2)
Example file : https://forge.brgm.fr/svnrepository/epos/trunk/instances/BoreholeView.xml
WFS query : http://resource.europe-geology.eu/service/wfsBorehole?service=wfs&version=2.0.2&request=GetFeature&typenames=gsmlp:BoreholeView&filter=<Filter><PropertyIsEqualTo><PropertyName>gsmlp:driller</PropertyName><Literal>AGIP</Literal></PropertyIsEqualTo></Filter>&count=1 

# others: please add

Sylvain

**Comment by ansorchr** [comment]
# EEA

EU Registry on Industrial Sites
- new data flow combining ePRTR and IED industrial sites data; first reporting, March 2018 
- Extension of INSPIRE PF
- http://cdrtest.eionet.europa.eu/help/ied_registry
- Example file (fake data): http://cdrtest.eionet.europa.eu/help/ied_registry/documents/Example%20XML/EUReg.example.gml

**Comment by hallin-pihlatie** [comment]
# SYKE

A Beta WFS service providing INSPIRE-data products from application schemas in the Protected Sites and Hydrography themes:  http://geoserver.ymparisto.fi/geoserver/wfs?service=wfs&version=2.0.0&request=GetCapabilities

Atom feed for the provision of Nature Protected Areas ja Natura 2000 sites according to the Protected Sites application schema, and a selection of feature types from the theme Hydrography theme  (GML, ETRS89 / LAEA): wwwd3.ymparisto.fi/d3/INSPIREAtom/inspireatomgml.xml

The data products returned (GMLs) are not identical, due to restrictions in to the provision of complex feature types in GeoServer&AppSchema.

Technical remark: When using the URI-type srsName "http://www.opengis.net/def/crs/EPSG/0/3035" the coordinates seem to be interpreted (by GDAL) in order (easting, northing), while the official axis order (according to the EPSG-registry) is (northing, easting). The situation can be solved by changing the coordinate system identifier manually to URN format "urn:ogc:def:crs:EPSG::3035. More information in GDAL ticket 6678.

**Comment by rouault** [comment]
> Technical remark: When using the URI-type srsName "http://www.opengis.net/def/crs/EPSG/0/3035" the coordinates seem to be interpreted (by GDAL) in order (easting, northing), while the official axis order (according to the EPSG-registry) is (northing, easting)

@hallin-pihlatie  The issue was fixed in GDAL 2.2 (actually since 2.1.2), and thus the GMLAS driver works out of the box.

**Comment by mhugo** [comment]
@rouault how is it resolved ? I had a similar issue here:
https://github.com/BRGM/gml_application_schema_toolbox/issues/7

I guess it is resolved by knowing which version of WFS is requested ? No chance ogr.CreateGeometryFromGML gets fixed ?
